/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-1月-2019 9:57:01 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `sc_user` CASCADE
;

/* Create Tables */

CREATE TABLE `sc_user`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`user_name` VARCHAR(50) NOT NULL COMMENT '用户名',
	`real_name` VARCHAR(50) NOT NULL,
	`header_pic` VARCHAR(100) NOT NULL,
	`password` VARCHAR(50) NOT NULL COMMENT '密码',
	`phone` VARCHAR(20) NULL COMMENT '手机号',
	`email` VARCHAR(50) NULL COMMENT '电子邮件',
	`type` VARCHAR(50) NOT NULL,
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_user_info` PRIMARY KEY (`id` ASC)
)
COMMENT = '管理员表'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `sc_user` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_user` 
 ADD CONSTRAINT `user_name_uniq` UNIQUE (`user_name` ASC)
;

ALTER TABLE `sc_user` 
 ADD CONSTRAINT `phone_uniq` UNIQUE (`phone` ASC)
;

ALTER TABLE `sc_user` 
 ADD CONSTRAINT `email_uniq` UNIQUE (`email` ASC)
;

ALTER TABLE `sc_user` 
 ADD INDEX `phone_index` (`phone` ASC)
;

ALTER TABLE `sc_user` 
 ADD INDEX `status_index` (`status` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
