/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 21-12月-2018 16:24:41 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `sc_menu` CASCADE
;

DROP TABLE IF EXISTS `sc_permission` CASCADE
;

DROP TABLE IF EXISTS `sc_role` CASCADE
;

DROP TABLE IF EXISTS `sc_role_menu` CASCADE
;

DROP TABLE IF EXISTS `sc_role_permission` CASCADE
;

DROP TABLE IF EXISTS `sc_setting` CASCADE
;

DROP TABLE IF EXISTS `sc_time_task` CASCADE
;

DROP TABLE IF EXISTS `sc_user` CASCADE
;

DROP TABLE IF EXISTS `sc_user_extends` CASCADE
;

DROP TABLE IF EXISTS `sc_user_role` CASCADE
;

/* Create Tables */

CREATE TABLE `sc_menu`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`parent_code` VARCHAR(50) NOT NULL COMMENT '父级编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`link_url` VARCHAR(50) NOT NULL COMMENT '链接地址',
	`sort` INT NULL DEFAULT 0 COMMENT '排序',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_menu` PRIMARY KEY (`id` ASC)
)
COMMENT = '菜单表'

;

CREATE TABLE `sc_permission`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`en_name` VARCHAR(50) NOT NULL COMMENT '英文缩写',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_permission` PRIMARY KEY (`id` ASC)
)
COMMENT = '权限表'

;

CREATE TABLE `sc_role`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_role` PRIMARY KEY (`id` ASC)
)
COMMENT = '角色表'

;

CREATE TABLE `sc_role_menu`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
	`menu_code` VARCHAR(50) NOT NULL COMMENT '菜单编码',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_role_menu` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `sc_role_permission`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
	`permission_code` VARCHAR(50) NOT NULL COMMENT '权限编码',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_role_permission` PRIMARY KEY (`id` ASC)
)
COMMENT = '角色权限关系表'

;

CREATE TABLE `sc_setting`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`parent_code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_setting` PRIMARY KEY (`id` ASC)
)
COMMENT = '系统相关配置表'

;

CREATE TABLE `sc_time_task`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`time` VARCHAR(50) NOT NULL COMMENT '定时区间',
	`exec_class` VARCHAR(50) NOT NULL COMMENT '执行类',
	`type` VARCHAR(50) NOT NULL COMMENT '类型',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`description` VARCHAR(50) NOT NULL COMMENT '描述',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_time_task` PRIMARY KEY (`id` ASC)
)
COMMENT = '定时任务'

;

CREATE TABLE `sc_user`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`user_name` VARCHAR(50) NOT NULL COMMENT '用户名',
	`password` VARCHAR(50) NOT NULL COMMENT '密码',
	`phone` VARCHAR(20) NULL COMMENT '手机号',
	`email` VARCHAR(50) NULL COMMENT '电子邮件',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_user_info` PRIMARY KEY (`id` ASC)
)
COMMENT = '管理员表'

;

CREATE TABLE `sc_user_extends`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`real_name` VARCHAR(50) NOT NULL COMMENT '真实姓名',
	`type` VARCHAR(50) NULL COMMENT '类型',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '修改时间',
	CONSTRAINT `PK_sc_user_extends` PRIMARY KEY (`id` ASC)
)
COMMENT = '管理员扩展表'

;

CREATE TABLE `sc_user_role`
(
	`id` INT NOT NULL,
	`uid` VARCHAR(50) NOT NULL,
	`user_code` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_user_role` PRIMARY KEY (`id` ASC)
)
COMMENT = '用户角色关系表'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `sc_menu` 
 ADD INDEX `code_uniq` (`code` ASC)
;

ALTER TABLE `sc_menu` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_role` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_role_menu` 
 ADD INDEX `role_menu` (`role_code` ASC, `menu_code` ASC)
;

ALTER TABLE `sc_role_permission` 
 ADD CONSTRAINT `role_permission` UNIQUE (`role_code` ASC, `permission_code` ASC)
;

ALTER TABLE `sc_setting` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_time_task` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_time_task` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `sc_time_task` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_user` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_user` 
 ADD INDEX `phone_index` (`phone` ASC)
;

ALTER TABLE `sc_user` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_user_extends` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_user_extends` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `sc_user_role` 
 ADD CONSTRAINT `user_role` UNIQUE (`user_code` ASC, `role_code` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
