system:
  #默认密码
  password: 123456
  #用户相关配置
  user:
    header:
      default: http://localhost:8080/image/header/default.jpg
      path: d:/image/header/
      url: http://localhost:8080/image/header/
    #用户状态父级编码
    status: SS1077457857042968576
    #用户类型父级编码
    type: SS1077393850122629120
  #菜单相关配置
  menu:
    #菜单状态
    status: SS1077459485556994048
  #定时任务相关配置 
  time_task:
    #定时任务类型
    type: SS1077741849222836224
    #定时任务状态
    status: SS1077459485556994048