# 开发环境配置
server: 
  application:
    name: system-api
  port: 8010
spring: 
  datasource:
    system:
      name: yql
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/systemcenter?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      filters: stat
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 1
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      maxWait: 60000
      #最大连接池数量
      maxActive: 20
      #最小连接池数量
      minIdle: 1
      #有两个含义：
      #1)Destroy线程会检测连接的间隔时间
      #2)testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      #议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。 PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    #host: 127.0.0.1
    #port: 7000
    #普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
    cluster:
      nodes: 
            - 127.0.0.1:7000
            - 127.0.0.1:7001
            - 127.0.0.1:7002
            - 127.0.0.1:7003
            - 127.0.0.1:7004
            - 127.0.0.1:7005
    expireSeconds: 120 
    #redis操作的超时时间
    commandTimeout: 10000
    pool: 
      # 池在给定时间可以分配的最大连接数。使用负值无限制。
      maxActive: 5000
      # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
      maxIdle: 30
      # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
      minIdle: 5
      # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
      maxWait: 3000
mybatis:
  mapperLocations: "classpath*:mappers/**/*.xml"
  typeAliasesPackage: org.system.entity

#定时任务配置
scheduled:
  pool:
    #线程池大小
    size: 10
